-- MySQL Script generated by MySQL Workbench
-- Thu Jan 12 22:13:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id_curso` INT UNSIGNED NOT NULL,
  `nome_curso` VARCHAR(100) NOT NULL,
  `turno_curso` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `id_aluno` INT UNSIGNED NOT NULL,
  `nome_aluno` VARCHAR(100) NOT NULL,
  `sobrenome_aluno` VARCHAR(100) NOT NULL,
  `cpf_aluno` VARCHAR(50) NOT NULL,
  `matricula_aluno` VARCHAR(50) NOT NULL,
  `email_aluno` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  `id_turma` INT UNSIGNED NOT NULL,
  `nome_turma` VARCHAR(100) NOT NULL,
  `matriculas_turma` VARCHAR(50) NOT NULL,
  `turno_turma` VARCHAR(50) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `cursos_id_curso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_turma`, `cursos_id_curso`),
  INDEX `fk_turmas_cursos_idx` (`cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_cursos`
    FOREIGN KEY (`cursos_id_curso`)
    REFERENCES `mydb`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores` (
  `id_professor` INT UNSIGNED NOT NULL,
  `nome_professor` VARCHAR(100) NOT NULL,
  `sobrenome_professor` VARCHAR(100) NOT NULL,
  `cpf_professor` VARCHAR(50) NOT NULL,
  `matricula_professor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_professor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos_has_professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos_has_professores` (
  `cursos_id_curso` INT UNSIGNED NOT NULL,
  `professores_id_professor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cursos_id_curso`, `professores_id_professor`),
  INDEX `fk_cursos_has_professores_professores1_idx` (`professores_id_professor` ASC) VISIBLE,
  INDEX `fk_cursos_has_professores_cursos1_idx` (`cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_professores_cursos1`
    FOREIGN KEY (`cursos_id_curso`)
    REFERENCES `mydb`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_professores_professores1`
    FOREIGN KEY (`professores_id_professor`)
    REFERENCES `mydb`.`professores` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores_has_cursos` (
  `professores_id_professor` INT UNSIGNED NOT NULL,
  `cursos_id_curso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`professores_id_professor`, `cursos_id_curso`),
  INDEX `fk_professores_has_cursos_cursos1_idx` (`cursos_id_curso` ASC) VISIBLE,
  INDEX `fk_professores_has_cursos_professores1_idx` (`professores_id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_professores_has_cursos_professores1`
    FOREIGN KEY (`professores_id_professor`)
    REFERENCES `mydb`.`professores` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professores_has_cursos_cursos1`
    FOREIGN KEY (`cursos_id_curso`)
    REFERENCES `mydb`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos_has_cursos` (
  `alunos_id_aluno` INT UNSIGNED NOT NULL,
  `cursos_id_curso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alunos_id_aluno`, `cursos_id_curso`),
  INDEX `fk_alunos_has_cursos_cursos1_idx` (`cursos_id_curso` ASC) VISIBLE,
  INDEX `fk_alunos_has_cursos_alunos1_idx` (`alunos_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_has_cursos_alunos1`
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `mydb`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_has_cursos_cursos1`
    FOREIGN KEY (`cursos_id_curso`)
    REFERENCES `mydb`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos_has_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos_has_alunos` (
  `cursos_id_curso` INT UNSIGNED NOT NULL,
  `alunos_id_aluno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cursos_id_curso`, `alunos_id_aluno`),
  INDEX `fk_cursos_has_alunos_alunos1_idx` (`alunos_id_aluno` ASC) VISIBLE,
  INDEX `fk_cursos_has_alunos_cursos1_idx` (`cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_alunos_cursos1`
    FOREIGN KEY (`cursos_id_curso`)
    REFERENCES `mydb`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_alunos_alunos1`
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `mydb`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos_has_professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos_has_professores` (
  `alunos_id_aluno` INT UNSIGNED NOT NULL,
  `professores_id_professor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alunos_id_aluno`, `professores_id_professor`),
  INDEX `fk_alunos_has_professores_professores1_idx` (`professores_id_professor` ASC) VISIBLE,
  INDEX `fk_alunos_has_professores_alunos1_idx` (`alunos_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_has_professores_alunos1`
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `mydb`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_has_professores_professores1`
    FOREIGN KEY (`professores_id_professor`)
    REFERENCES `mydb`.`professores` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores_has_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores_has_alunos` (
  `professores_id_professor` INT UNSIGNED NOT NULL,
  `alunos_id_aluno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`professores_id_professor`, `alunos_id_aluno`),
  INDEX `fk_professores_has_alunos_alunos1_idx` (`alunos_id_aluno` ASC) VISIBLE,
  INDEX `fk_professores_has_alunos_professores1_idx` (`professores_id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_professores_has_alunos_professores1`
    FOREIGN KEY (`professores_id_professor`)
    REFERENCES `mydb`.`professores` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professores_has_alunos_alunos1`
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `mydb`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas_has_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas_has_alunos` (
  `turmas_id_turma` INT UNSIGNED NOT NULL,
  `turmas_cursos_id_curso` INT UNSIGNED NOT NULL,
  `alunos_id_aluno` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`turmas_id_turma`, `turmas_cursos_id_curso`, `alunos_id_aluno`),
  INDEX `fk_turmas_has_alunos_alunos1_idx` (`alunos_id_aluno` ASC) VISIBLE,
  INDEX `fk_turmas_has_alunos_turmas1_idx` (`turmas_id_turma` ASC, `turmas_cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_has_alunos_turmas1`
    FOREIGN KEY (`turmas_id_turma` , `turmas_cursos_id_curso`)
    REFERENCES `mydb`.`turmas` (`id_turma` , `cursos_id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_has_alunos_alunos1`
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `mydb`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos_has_turmas` (
  `alunos_id_aluno` INT UNSIGNED NOT NULL,
  `turmas_id_turma` INT UNSIGNED NOT NULL,
  `turmas_cursos_id_curso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alunos_id_aluno`, `turmas_id_turma`, `turmas_cursos_id_curso`),
  INDEX `fk_alunos_has_turmas_turmas1_idx` (`turmas_id_turma` ASC, `turmas_cursos_id_curso` ASC) VISIBLE,
  INDEX `fk_alunos_has_turmas_alunos1_idx` (`alunos_id_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_has_turmas_alunos1`
    FOREIGN KEY (`alunos_id_aluno`)
    REFERENCES `mydb`.`alunos` (`id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_has_turmas_turmas1`
    FOREIGN KEY (`turmas_id_turma` , `turmas_cursos_id_curso`)
    REFERENCES `mydb`.`turmas` (`id_turma` , `cursos_id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores_has_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores_has_turmas` (
  `professores_id_professor` INT UNSIGNED NOT NULL,
  `turmas_id_turma` INT UNSIGNED NOT NULL,
  `turmas_cursos_id_curso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`professores_id_professor`, `turmas_id_turma`, `turmas_cursos_id_curso`),
  INDEX `fk_professores_has_turmas_turmas1_idx` (`turmas_id_turma` ASC, `turmas_cursos_id_curso` ASC) VISIBLE,
  INDEX `fk_professores_has_turmas_professores1_idx` (`professores_id_professor` ASC) VISIBLE,
  CONSTRAINT `fk_professores_has_turmas_professores1`
    FOREIGN KEY (`professores_id_professor`)
    REFERENCES `mydb`.`professores` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professores_has_turmas_turmas1`
    FOREIGN KEY (`turmas_id_turma` , `turmas_cursos_id_curso`)
    REFERENCES `mydb`.`turmas` (`id_turma` , `cursos_id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas_has_professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas_has_professores` (
  `turmas_id_turma` INT UNSIGNED NOT NULL,
  `turmas_cursos_id_curso` INT UNSIGNED NOT NULL,
  `professores_id_professor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`turmas_id_turma`, `turmas_cursos_id_curso`, `professores_id_professor`),
  INDEX `fk_turmas_has_professores_professores1_idx` (`professores_id_professor` ASC) VISIBLE,
  INDEX `fk_turmas_has_professores_turmas1_idx` (`turmas_id_turma` ASC, `turmas_cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_has_professores_turmas1`
    FOREIGN KEY (`turmas_id_turma` , `turmas_cursos_id_curso`)
    REFERENCES `mydb`.`turmas` (`id_turma` , `cursos_id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_has_professores_professores1`
    FOREIGN KEY (`professores_id_professor`)
    REFERENCES `mydb`.`professores` (`id_professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
